version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: doc/source/conf.py

# Simulate pip install .[doc]
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc
